# Generated by Django 3.1.2 on 2021-03-11 01:59

import blog.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='Заголовок статьи')),
                ('article_text', models.TextField(verbose_name='Текст статьи')),
                ('article_date', models.DateTimeField(default=datetime.date.today, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Статью',
                'verbose_name_plural': '1Статьи',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_adress', models.TextField(verbose_name='Адреса')),
                ('contact_email', models.TextField(verbose_name='Email')),
                ('contact_phone', models.TextField(verbose_name='Телефон')),
                ('contact_instagram', models.TextField(verbose_name='Полная ссылка на инстаграм')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_title', models.CharField(max_length=200, verbose_name='Название партнера')),
                ('sponsor_text', models.TextField(verbose_name='Описание')),
                ('sponsor_link', models.TextField(blank=True, verbose_name='Ссылка на сайт')),
            ],
            options={
                'verbose_name': 'партнер',
                'verbose_name_plural': 'партнеры',
            },
        ),
        migrations.CreateModel(
            name='SponsorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', validators=[blog.models.SponsorImage.validate_image], verbose_name='Логотип партнера')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.sponsor')),
            ],
            options={
                'verbose_name': 'Логотип партнера',
                'verbose_name_plural': 'Логотип партнера',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=300, verbose_name='Текст комментария')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', validators=[blog.models.ArticleImage.validate_image], verbose_name='Фотографии статьи')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.article')),
            ],
            options={
                'verbose_name': 'Фотография статьи',
                'verbose_name_plural': 'Фотографии статьи',
            },
        ),
    ]
