# Generated by Django 3.1.2 on 2021-03-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статью', 'verbose_name_plural': '1 Статьи'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': '3 Контакты'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'партнер', 'verbose_name_plural': '2 Партнеры'},
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='sponsor_text',
        ),
    ]
