# Generated by Django 3.1.2 on 2020-11-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_comment_comment_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
