# Generated by Django 3.1.2 on 2020-12-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201130_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_title', models.CharField(max_length=200, verbose_name='Название спонсора')),
                ('sponsor_text', models.TextField(verbose_name='Описание')),
                ('sponsor_image', models.ImageField(upload_to='', verbose_name='Логотип спонсора')),
            ],
            options={
                'verbose_name': 'Спонсоры',
                'verbose_name_plural': 'Спонсор',
            },
        ),
    ]
