# Generated by Django 3.1.2 on 2020-12-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_sponsor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'Спонсор', 'verbose_name_plural': 'Спонсоры'},
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_image',
            field=models.ImageField(upload_to='media/', verbose_name='Логотип спонсора'),
        ),
    ]
