# Generated by Django 3.1.2 on 2020-12-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201205_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_image',
            field=models.ImageField(height_field=100, upload_to='media/', width_field=100),
        ),
    ]
