# Generated by Django 3.1.2 on 2020-12-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201206_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Логотип спонсора'),
        ),
    ]
