# Generated by Django 3.1.2 on 2020-12-06 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201206_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Логотип спонсора')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagesSponsor', to='blog.sponsor')),
            ],
            options={
                'verbose_name': 'Логотип спонсора',
                'verbose_name_plural': 'Логотипы спонсора',
            },
        ),
    ]
