# Generated by Django 3.1.2 on 2020-12-06 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_sponsor_sponsor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorimage',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.sponsor'),
        ),
    ]
