# Generated by Django 3.1.2 on 2021-01-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20201206_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='sponsor_link',
            field=models.TextField(default=1, verbose_name='Ссылка на сайт'),
            preserve_default=False,
        ),
    ]
