# Generated by Django 3.1.2 on 2021-01-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_sponsor_sponsor_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_adress', models.TextField(verbose_name='Адреса')),
                ('contact_email', models.TextField(verbose_name='Email')),
                ('contact_phone', models.TextField(verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
