# Generated by Django 3.1.2 on 2021-02-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210201_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_instagram',
            field=models.TextField(default=0, verbose_name='Полная ссылка на инстаграм'),
            preserve_default=False,
        ),
    ]
