# Generated by Django 3.1.2 on 2021-02-14 02:31

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_contact_contact_instagram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'партнер', 'verbose_name_plural': 'партнеры'},
        ),
        migrations.AlterModelOptions(
            name='sponsorimage',
            options={'verbose_name': 'Логотип партнера', 'verbose_name_plural': 'Логотип партнера'},
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_link',
            field=models.TextField(blank=True, verbose_name='Ссылка на сайт'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_title',
            field=models.CharField(max_length=200, verbose_name='Название партнера'),
        ),
        migrations.AlterField(
            model_name='sponsorimage',
            name='image',
            field=models.ImageField(upload_to='', validators=[blog.models.SponsorImage.validate_image], verbose_name='Логотип партнера'),
        ),
    ]
